name: child1
on: 
  workflow_call:
    inputs:
      name:
        type: string
        required: true
    outputs:
      message: 
        value: ${{ jobs.job.outputs.message }}
        description: "This out message"
jobs:
  job:
    runs-on: ubuntu-latest
    outputs: 
      message: ${{ steps.runtask.outputs.firstout }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: task
        id: runtask
        run: |
          echo ${{inputs.name}}
          ls -ltr
          echo "firstout=hello output" >> $GITHUB_OUTPUT
